APPS-sookmyung/2024-APPS-Exhibition-Webpage

README.md

close #1
<br />
- README 문서 작성
<br />

#1 [DOCS] README 문서 작성

---

.gitignore

close #4
<br />
- .gitignore 파일 생성
<br />

#4 [FEAT] .gitignore 파일 생성

---

src/pages/AboutAppsPage/AboutAppsPage.jsx
src/pages/AboutAppsPage/AboutAppsPage.style.jsx

close #14
<br />
- About 페이지 소개 부분 구현
<br />
|    About 페이지 소개 부분     |
| <img width='600' src='https://github.com/user-attachments/assets/7bab62c3-1b30-4c09-a9ea-57704ae819c7'> |
<br />

#14 [FEAT] About 페이지 소개 부분 구현

---

src/components/Header/Header.jsx
src/components/Header/Header.style.jsx

close #24
<br />
- header 디테일 수정
- hover 효과 적용
- 배경색 변경 
<br />
|    `header` 컴포넌트    |
| <img width='600' src='https://github.com/user-attachments/assets/75ac9638-5dc1-4437-886e-dbd62c453f13'> |
<br />

#24 [DESIGN] header 디테일 수정

---

src/pages/HomePage/HomePage.jsx
src/pages/HomePage/HomePage.style.jsx

close #39
<br />
- 홈페이지 내 `함께 여정을 떠나볼까요?` 섹션 구현
- hover 효과 적용
<br />
|    `함께 여정을 떠나볼까요?`    |
| <img width='600' src='https://github.com/user-attachments/assets/7650f964-cd44-4bb0-8370-642150db2c6d'> |
<br />
- `링크 공유하기`는 배포 후에 링크 추가 예정
<br />

#39 [FEAT] 홈페이지 내 `함께 여정을 떠나볼까요?` 섹션 구현

---

src/database/index.js
src/pages/HomePage/HomePage.jsx
src/pages/HomePage/HomePage.style.jsx

close #31
<br />
- homepage 내 import 오류 해결
<br />

#31 [FIX] homepage 내 import 오류 해결

---

src/components/AboutAppsCoreValueCard/AboutAppsCoreValueCard.jsx
src/components/AboutAppsCoreValueCard/AboutAppsCoreValueCard.style.jsx
src/components/AboutAppsCoreValueCard/index.js
src/components/AboutAppsIconicCard/index.js
src/components/index.js
src/pages/HomePage/HomePage.jsx
src/pages/HomePage/HomePage.style.jsx

close #43
<br />
- about apps 내 선 겹침현상 해결 및 그라데이션 모션 적용
<br />
|    `About APPS`     |
| <img width='600' src='https://github.com/user-attachments/assets/870f418a-0647-4905-8ca6-771221fa9592'> |
<br />

#43 [FEAT] `About APPS` 내 선 겹침현상 해결 및 그라데이션 모션 적용

---

src/components/Header/Header.style.jsx
src/pages/AboutAppsPage/AboutAppsPage.jsx
src/pages/AboutAppsPage/AboutAppsPage.style.jsx
src/pages/HomePage/HomePage.style.jsx

close #51
<br />
- Header 상단에 고정
<br />
|    `Header`     |
| <img width='600' src='https://github.com/user-attachments/assets/744740ce-f62c-4637-a796-7a1516f4a795'> |
<br />

#51 [FEAT] Header 상단에 고정

---

src/components/Footer/Footer.jsx
src/components/Footer/Footer.style.jsx
src/components/PageLayout/PageLayout.jsx
src/pages/AboutAppsPage/AboutAppsPage.style.jsx
src/pages/HomePage/HomePage.style.jsx

close #53
<br />
- 홈페이지, about APPS 페이지 내 footer 적용
- footer CSS 속성 일부 수정
<br />
|    `footer`    |
| <img width='600' src='https://github.com/user-attachments/assets/98ae4c40-8fbc-4735-be2d-496bfee10cee'> |
<br />

#53 [FEAT] 홈페이지, about APPS 페이지 내 footer 적용 및 footer CSS 속성 일부 수정

---

src/components/ActivityCard/ActivityCard.jsx
src/components/ActivityCard/ActivityCard.style.jsx
src/pages/AboutAppsPage/AboutAppsPage.style.jsx

close #84
<br />
- About 페이지 반응형 수정
<br />
|    About 페이지 반응형 수정     |
| <img width='600' src='https://github.com/user-attachments/assets/6651965e-a264-4b2a-a144-4d5b09ba05cb'> |
<br />

#84 [DESIGN] About 페이지 반응형 수정

---

src/components/SocialMediaLinkCards/SocialMediaLinkCards.jsx

close #86
<br />
- SNS 새 창 열기 속성 적용 (링크드인, 인스타그램)
<br />

#86 [FEAT] SNS 새 창 열기 속성 적용

---

src/pages/HomePage/HomePage.jsx

close #92
<br />
- 링크 공유하기 버튼 클릭시 링크 복사되는 기능 구현
<br />
|    홈화면 내 '링크 공유하기' 버튼 클릭시 alert창 뜸     |
| <img width='600' src='https://github.com/user-attachments/assets/b42025e6-cf58-493f-96ee-06ac576de790'> |
<br />
지금은 링크 공유하기 버튼 클릭시, alert 창이 뜨도록 구현했습니다.
시간이 허락한다면..^^ 토스트 메세지가 뜨는 것으로 수정할까 하는데 
혹시 작업이 어렵게 되면, 링크 복사만 하고 alert창은 제거할게요:)
<br />

#92 [FEAT] 링크 공유하기 버튼 클릭시 링크 복사되는 기능 구현

---

src/components/ActivityCard/ActivityCard.jsx
src/components/ActivityCard/ActivityCard.style.jsx
src/components/CalendarCard/CalendarCard.jsx
src/components/CalendarCard/CalendarCard.style.jsx
src/components/FallingBlocks/FallingBlocks.jsx
src/components/FallingBlocks/FallingBlocks.style.jsx
src/database/styledSquareColorCards.js
src/pages/AboutAppsPage/AboutAppsPage.jsx
src/pages/AboutAppsPage/AboutAppsPage.style.jsx

close #98
<br />
- About 페이지 상단 모션 반응형 수정
-  Apps 소개 , `ActivityCard`, `CalendarCard` 반응형 수정
<br />
|    About 페이지 상단 모션 반응형 수정     |
| <img width='600' src='https://github.com/user-attachments/assets/3aae35c6-62d8-459a-add8-fd4b047e1932'> |
<br />

#98 [FEAT] About 페이지 상단 모션 반응형 수정

---

src/components/MemberCard/MemberCard.style.jsx

close #112 
<br />
- 멤버 이미지 정렬 재수정
<br />
|    멤버 이미지 정렬 재수정     |
| <img width='600' src='https://github.com/user-attachments/assets/78ea5dac-704a-4045-855f-9a0fcea4c576'> |
<br />

#112 [FEAT] 멤버 이미지 정렬 재수정

---

src/components/ReviewCard/ReviewCard.style.jsx
src/pages/ProjectPage/ProjectPage.style.jsx

close #125 
<br />
-  X버튼 사이즈 키우기
- 유튜브 위 마진 좁게
- 줄바꿈 단어 단위로

#125 [FEAT] 프로젝트 페이지: 디테일 수정

---

src/components/MemberCard/MemberCard.jsx
src/components/MemberCard/MemberCard.style.jsx
src/components/Modal/Modal.jsx
src/components/Modal/Modal.style.jsx
src/pages/AboutAppsPage/AboutAppsPage.jsx
src/pages/AboutAppsPage/AboutAppsPage.style.jsx

close #114 
<br />
- 모달창 반응형 수정
- 반응형 모달 패딩값 줄이기
- 반응형 모달 MemberCard 사이즈 줄이기
- MemberList 반응형 수정
- 줄 바꿈 단어 단위로 수정
- Modal 컴포넌트에서 이벤트 리스너 최적화
<br />
- divider 문제 빼고는 해결했어요!
<br />

#114 [FIX] MemberCard, Modal 반응형 수정

---

src/pages/HomePage/HomePage.jsx
src/pages/HomePage/HomePage.style.jsx

close #138
<br />
- 홈 화면 내 상단 배경화면 반응형 재적용
<br />

#138 [FIX] 홈 화면 내 상단 배경화면 반응형 재적용

---

src/pages/ProjectPage/ProjectPage.jsx

close #142
<br />
- 유튜브 미리보기 이슈 해결
<br />
|    유튜브 미리보기 이슈 해결     |
| <img width='600' src='https://github.com/user-attachments/assets/c160e49c-cf03-4a04-81d8-83457a75a7b5'> |
<br />

#142 [FIX] 유튜브 미리보기 이슈 해결

---

src/components/ProjectCardList/ProjectCardList.jsx
src/components/ProjectCardList/ProjectCardList.style.jsx

close #141
<br />
- 프로젝트 카드 높이가 영역안에서 최대가 되도록 수정
<br />

#141 [FIX] 프로젝트 카드 높이가 영역안에서 최대가 되도록 수정

---

src/pages/HomePage/HomePage.jsx

close #146
<br />
- 부원들이 말하는 APPS 영역 임시 주석처리
<br />

#146 [REMOVE] 부원들이 말하는 APPS 영역 임시 주석처리

---

src/pages/ProjectPage/ProjectPage.jsx
src/pages/ProjectPage/ProjectPage.style.jsx

close #150
<br />
- 프로젝트 공유하기 활성화
<br />
|    프로젝트 공유하기 활성화     |
| <img width='600' src='https://github.com/user-attachments/assets/41edac0d-15d8-4df3-8f81-24b5965ec5d8'> |
<br />

#150 [FEAT] 프로젝트 공유하기 활성화

---

src/components/Modal/Modal.style.jsx

close #136 
<br />
- 모달 창 테두리 추가
- QA 간격 조정
- 줄 간격 수
<br />
|    모달 디테일 수정     |
| <img width='600' src='https://github.com/user-attachments/assets/9b5fc502-17a6-4588-a3da-e96be3c77561'> |
<br />

#136 [FIX] 모달 디테일 수정

---

src/components/Modal/Modal.jsx

close #153 
<br />
- 모달 밖 스크롤 방지
<br />
|    모달 밖 스크롤 방지     |
| <img width='600' src='https://github.com/user-attachments/assets/35d0dfde-8344-4013-b1ae-2a9617e85d45'> |
<br />

#153 [FIX] 모달 밖 스크롤 방지

---

src/pages/ProjectPage/ProjectPage.jsx

close #156
<br />
- 프로젝트 페이지 모바일 버전에서 이상한 이미지 뜨는 이슈 해결
<br />
|    (스크린샷 타이틀)     |
| <img width='600' src=''> |
<br />

#156 [FIX] 프로젝트 페이지 모바일 버전에서 이상한 이미지 뜨는 이슈 해결

---

src/components/Header/Header.jsx
src/components/ProjectCardList/ProjectCardList.style.jsx
src/pages/HomePage/HomePage.jsx
src/pages/ProjectPage/ProjectPage.jsx

close #162
<br />
- X 버튼 클릭시 홈화면의 프로젝트 목록 섹션으로 이동
<br />

#162 [FEAT] X 버튼 클릭시 홈화면의 프로젝트 목록 섹션으로 이동

---

src/pages/ProjectPage/ProjectPage.style.jsx

close #166
<br />
- 폰트 적용 및 프로젝트 공유하기 버튼 높이 수정
<br />

#166 [FEAT] 폰트 적용 및 프로젝트 공유하기 버튼 높이 수정

---

src/components/MemberFeedbackCardList/MemberFeedbackCardList.jsx
src/components/MemberFeedbackCardList/MemberFeedbackCardList.style.jsx
src/database/memberFeedback.js
src/database/projectList.js
src/pages/HomePage/HomePage.jsx
src/pages/ProjectPage/ProjectPage.jsx
src/pages/ProjectPage/ProjectPage.style.jsx

close #87
<br />
- 부원들이 말하는 APPS 움직이는 모션 마저 구현 
<br />

#87 [FEAT] 부원들이 말하는 APPS 움직이는 모션 구현 

---

public/images/icons/divider.svg
src/components/Modal/Modal.style.jsx

close #163 
<br />
- 모달 내 선 반응형 수정
<br />
|    모달 내 선 반응형 수정     |
| <img width='600' src=''> |
<br />

#163 [FIX] 모달 내 선 반응형 수정

---

src/pages/AboutAppsPage/AboutAppsPage.jsx
src/pages/HomePage/HomePage.jsx
src/pages/ProjectPage/ProjectPage.jsx
src/pages/ProjectPage/ProjectPage.style.jsx

close #174
<br />
- `프로젝트 공유하기` `hover` 효과 적용
- 공유하기 -> 복사하기 이름 변경
- 복사되는 링크 변경
<br />
|    프로젝트 공유하기 이름 변경 및 호버 효과 적용     |
| <img width='400' src='https://github.com/user-attachments/assets/778518be-f9f8-4885-9102-a6ea6f1539db'> |
<br />

#174 [FEAT] 프로젝트 공유하기 이름 변경 및 호버 효과 적용

---

src/components/DeveloperCard/DeveloperCard.style.jsx

close #176 
<br />
- 프로젝트 페이지 `DeveloperCard` 커서 삭제
<br />

#176 [REMOVE] 프로젝트 페이지 `DeveloperCard` 커서 삭제

---

src/pages/HomePage/HomePage.jsx

close #180
<br />
- 닫기 버튼 클릭 시 홈 화면 맨 위로 돌아감 이슈 해결
<br />

#180 [FIX] 닫기 버튼 클릭 시 홈 화면 맨 위로 돌아감 이슈 해결

---

src/database/projectList.js
src/pages/ProjectPage/ProjectPage.jsx

#186 [MODIFY] 데이터 일부 변경

---

src/database/projectList.js

close #189
<br />
- 카공도 회고 및 유튜브 링크 추가
<br />

#189 [FEAT] 카공도 회고 및 유튜브 링크 추가

---

src/database/projectList.js

close #186
<br />
- 위렛 영상 추가
<br />

#186 [FEAT] 위렛 영상 추가

---

src/database/projectList.js

close #194
<br />
- 유튜브 URL 변경
<br />

#194 [FIX] 유튜브 URL 변경

---

public/index.html

close #202
<br />
- 구글 애널리틱스 코드 추가

#202 [FEAT] 구글 애널리틱스 코드 추가
